name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install system dependencies
        run: sudo apt update && sudo apt install -y make nasm

      - name: Compile OS
        run: make
