name: Build

on: push

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install system dependencies
        run: sudo apt update && sudo apt install -y make nasm xorriso

      - name: Compile OS
        run: make

      - name: Get commit number
        id: buildnum
        run: echo "num=$(git rev-list --count HEAD)" >> $GITHUB_OUTPUT

      - name: Get commit message
        id: commit
        run: echo "msg=$(git log -1 --pretty=%s)" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          name: Build ${{ steps.buildnum.outputs.num }}
          tag_name: build-${{ steps.buildnum.outputs.num }}
          prerelease: true
          body: ${{ steps.commit.outputs.msg }}
          files: clippyos.iso
